- docs/README.md
- docs/http-requests.md
- docs/json.md
- docs/rest.md
- docs/statics.md
- docs/tutorial.md
It needs to be developed. Since I'm not master at Crystal/Kemal, I couldn't cover all the features.
For the future, these are the concerns about writing documentation:
- It should be clean, *"tech-term-free"*.
- Think about the very beginners.
- Cover everything, never pass even the smallest features / functionalities to document.
- Needs an API doc.
- Tutorial should be improved.
- Needs an example project.
- Needs a boilerplate or scaffolding tool, like "kemal init" or something.
Keep up good work.
> Add documentation.

- spec/asset/layout.ecr
- spec/view_spec.cr
- src/kemal/view.cr
It should be improved in the future.
> Add layout support for render macro.

- src/kemal/param_parser.cr
This is very early implementation of parse_url_params. It should be implemented more elegant way.
> Implement parse_url_params

- .gitignore
- shard.yml
- src/kemal/handler.cr
- src/kemal/route.cr
Radix algorithm makes the route search faster (about **~6x**).
**Radix Tree search on 200 routes (to find the last route):**
```
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     2.54ms  767.82us   8.36ms   88.07%
Req/Sec     1.97k   261.30     3.98k    97.51%
39501 requests in 10.10s, 3.39MB read
```
**`.each` based lookup search on 200 routes (to find the last route)**
```
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    15.60ms    4.43ms  32.48ms   88.84%
Req/Sec   321.82      7.86   333.00     55.00%
6424 requests in 10.03s, 564.61KB read
```
When searching in lower number of routes, radix search and loop based search are almost same.
> Implement radix algorithm for routing (using Beryl)

- shard.yml
@luislavena's original Radix-tree implementation would be better to depend. Mine was just a fork.
> Change radix to @luislavena's original version

- samples/json_api.cr
There is a new syntax for this now. You need to write env.response.content_type
> Updating json sample

- README.md
Based on the @sdogruyol's latest test mentioned in `crystal-tr` Slack.
> Update super-duper speedy values 🚀🚀🚀

- README.md
Added some emojis to cleaner expression
> Fancier titles.

- spec/middleware/filters_spec.cr
- src/kemal/middleware/filters.cr
Sinatra Filters implementation as a middleware. http://www.sinatrarb.com/intro.html#Filters
> Basic filter implementation, similar to Sinatra.

- _docs/filters.md
> Updating docs for new filter api

- _docs/filters.md
> Updating docs for mulitple blocks per route filter.

- _docs/filters.md
Strings in Crystal must be in double quotes!
> Fix typo with quotes

- src/kemal/config.cr
This came in contradiction with the docs.
> Only set @logger when not previously set

- _docs/deployment.md
It threw SSL errors. This one seems to work fine
> The zamath build pack did not work

- spec/asset/hello_with_content_for.ecr
- spec/asset/layout_with_yield.ecr
- spec/view_spec.cr
- src/kemal/helpers.cr
Adds content_for and yield_content helpers. Thanks @RX14
> Content for

- _docs/context.md
It should render "Kemal cool = true" and not  "Kemal is cool"
> Fix last line about string about output

- src/kemal/static_file_handler.cr
Added some mime type for images. Very new to crystal so hopefully this is ok.
Without this they default to octet, which just does a download
> added mime types

- shard.yml
- spec/helpers_spec.cr
- src/kemal.cr
- src/kemal/cli.cr
- src/kemal/helpers/helpers.cr
This PR adds multipart support and fixes https://github.com/sdogruyol/kemal/issues/40 . Thanks @RX14.
```crystal
post "/upload" do |env|
parse_multipart(env) do |field, data|
image1 = data if field == "image1"
image2 = data if field == "image2"
"Upload complete"
end
end
```
> Add multipart support <3

- _docs/context.md
> Adds request properties section

- _docs/sessions.md
> Add example for changing session cookie name

- shard.yml
I just ran into luislavena/radix#9
> Update Radix to 0.3.2

- src/kemal/param_parser.cr
Waiting for Crystal 0.20.0 to be merged 👍
> Treat body as IO in param_parser

- shard.yml
Fixes #293 
Thanks @luislavena for great support as always 💯
> Update radix to 0.3.6. Fixes #293

- src/kemal/file_upload.cr
Related to crystal-lang/crystal/issues/4085
> apply :nodoc: only to Kemal::FileUpload instead of the whole Kemal

- src/kemal/helpers/helpers.cr
- src/kemal/static_file_handler.cr
Removed some duplicate code and enhances send file with mime-types, gzip and byte ranges.
> moved static file handler code to send_file

- src/kemal/route.cr
These properties would come handy during the `Context#route_lookup` introspection I'm doing in `raven.cr`.
> Add getters to Route#{path,method}

- spec/param_parser_spec.cr
- src/kemal/ext/params.cr
- src/kemal/ext/request.cr
This modifies `HTTP::Params.[]` to fetch all params 👍 Fixes #326 
Now one can access an Array in the POST body like the rest
> Modiy HTTP::Params.[] to fetch all params

- src/kemal/helpers/templates.cr
Add responsive width to Kemal logo.
> 404 responsive Kemal logo

- shard.yml
Radix has been updated => https://github.com/luislavena/radix/releases
Changes => https://github.com/luislavena/radix/compare/v0.3.7...v0.3.8
> Upgrade radix version

- spec/run_spec.cr
Code duplicate: two specs with exactly same code.
> Remove duplicate spec

- .travis.yml
- src/kemal.cr
This seems to fix it. Would you like me to update the travis tests to run in --release too? This would have failed if that had been set.
> fix for #399

- src/kemal.cr
- src/kemal/common_exception_handler.cr
- src/kemal/common_log_handler.cr
- src/kemal/config.cr
- src/kemal/dsl.cr
- src/kemal/ext/context.cr
- src/kemal/filter_handler.cr
- src/kemal/handler.cr
- src/kemal/helpers/helpers.cr
- src/kemal/helpers/macros.cr
- src/kemal/init_handler.cr
- src/kemal/param_parser.cr
- src/kemal/route.cr
- src/kemal/route_handler.cr
- src/kemal/websocket.cr
- src/kemal/websocket_handler.cr
> Prettify docs

- src/kemal/handler.cr
- src/kemal/param_parser.cr
> Fixed macros indentation

- src/kemal/helpers/utils.cr
A very small change. Added the webm mime type to utils.cr
> Add webm mime type to utils.cr

- spec/param_parser_spec.cr
- spec/route_handler_spec.cr
- src/kemal/param_parser.cr
> Crystal 0.24.2: Don't use JSON::Type, use JSON::Any instead

- spec/exception_handler_spec.cr
- spec/handler_spec.cr
- spec/helpers_spec.cr
- spec/init_handler_spec.cr
- spec/log_handler_spec.cr
- spec/param_parser_spec.cr
- spec/route_handler_spec.cr
- spec/route_spec.cr
- spec/spec_helper.cr
- spec/static_file_handler_spec.cr
- spec/websocket_handler_spec.cr
- src/kemal.cr
- src/kemal/exception_handler.cr
- src/kemal/helpers/templates.cr
Fixes some code smells reported by [Ameba v0.6.0](https://github.com/veelenga/ameba/releases/tag/v0.6.0).
> <small>Ameba is a static code analysis tool for the Crystal language</small>
Fixing issues reported by static analysis is a good practice. It makes a code more robust and errorless. 
None, since each change is done manually and verified.
> Code fixes reported by static code analysis

- spec/param_parser_spec.cr
- spec/route_handler_spec.cr
- spec/static_file_handler_spec.cr
- spec/websocket_handler_spec.cr
- src/kemal.cr
- src/kemal/config.cr
- src/kemal/helpers/helpers.cr
- src/kemal/param_parser.cr
- src/kemal/static_file_handler.cr
> Crystal next

- CHANGELOG.md
- src/kemal/param_parser.cr
This fixes https://github.com/kemalcr/kemal/issues/455.
Edit: As @straight-shoota mentioned, this is a breaking change for good :+1:
> Simplify file upload parsing and support multiple uploads with same name

- src/kemal.cr
Fix breaking change introduced in crystal-lang/crystal#5960 for compatibility with the upcoming release Crystal 0.26.0.
> Update to use HTTP::Server#bind_ssl

- spec/spec_helper.cr
- src/kemal/route_handler.cr
Fixes #488 
%20 - %25 overall performance🚀 
None
> Cache HTTP routes

- src/kemal.cr
- src/kemal/cli.cr
- src/kemal/config.cr
- src/kemal/filter_handler.cr
- src/kemal/handler.cr
- src/kemal/helpers/helpers.cr
- src/kemal/helpers/utils.cr
- src/kemal/log_handler.cr
- src/kemal/param_parser.cr
- src/kemal/route_handler.cr
- src/kemal/static_file_handler.cr
- src/kemal/websocket_handler.cr
This adds optimizations for variable and string allocations.
This benchmark shows that concatenation is more performant than interpolation to append chars/strings (at least up to 3 variables)
```crystal
require "benchmark"
STR = "string"
Benchmark.ips do |x|
x.report("1 char with 2 strings concat") do
'/' + STR + STR
end
x.report("2 strings with 1 char concat") do
STR + STR + '/'
end
x.report("3 strings concat") do
STR + STR + STR
end
x.report("2 strings with 1 char interpolation") do
"/#{STR}#{STR}"
end
x.report("2 strings with 1 char concat") do
STR + STR + '/'                                 
end
x.report("1 strings with 1 char interpolation") do
"/#{STR}"
end
x.report("String.build") do
String.build do |str|
str << '/'
str << STR
end
end
end
```
Results:
```
1 char with 2 strings …
```
> Add allocation optimizations

- src/kemal/handler.cr
> Use compile-time StringLiteral#downcase instead of runtime String#downcase

- spec/exception_handler_spec.cr
- src/kemal/exception_handler.cr
> Do not try to call ExceptionHandler#call_exception_with_status_code on a closed response

- spec/helpers_spec.cr
- src/kemal/route_handler.cr
fix https://github.com/kemalcr/kemal/issues/542
> fix process request when a response already closed

- src/kemal/websocket_handler.cr
There is another issue with Kemal in Crystal 0.35.0. Websockets are broken.
I create a repository where you can reproduce an issue https://github.com/mamantoha/kemal_websocket_issue
Run
```
crystal server.cr
```
Open http://localhost:3000
> fix websocket issue

- CHANGELOG.md
- shard.yml
The time has come to finally make Kemal 1.0.0 after 5+ years 🚀 
All the specs are already green in Crystal 1.0.0-dev 👍 
Waiting on https://github.com/crystal-lang/crystal/pull/10500 😄
> Release 1.0.0

- src/kemal/ext/response.cr
> Ignore HTTP::Server::Response patching for crystal >= 1.3.0

- src/kemal/helpers/helpers.cr
Replaced the loop of `skip` calls to a single `seek`.
It can save several seconds of time to load big movie file.
> Eliminated several seconds of delay when loading big mp4 file

- src/kemal/static_file_handler.cr
Fixes https://github.com/kemalcr/kemal/issues/643
> fix static file handler

- shard.yml
Remove version restriction on Ameba and keep it in the latest stage, this will fix the issue present in the CI
> Fixes issues present in the CI

- src/kemal/helpers/helpers.cr
Respect the `without_zlib` build flag, like the [stdlib itself does](https://github.com/crystal-lang/crystal/blob/c6f3552f5be159eb06c8f348c6b9e23ff7f17dbc/src/http/server/handlers/compress_handler.cr).
:woman_shrugging:
Makes it possible to avoid a zlib dependency. My current use case is actually building for WebAssembly.
None? :smile:
> helpers: Support building without_zlib

- src/kemal/helpers/exceptions.cr
Fixes recent changes to `CustomException` introduced by #671 and bef73510003637fa74aab93cf7d98cf287978128.
I'm not sure TBH why they were introduced in the first place, but nvm 🤷‍♂️ 
This makes the CI 💚 again.
> Fix recent changes to `CustomException`

- CHANGELOG.md
> Tweak CHANGELOG.md

- spec/static_file_handler_spec.cr
- src/kemal/config.cr
- src/kemal/helpers/helpers.cr
> Use context instead of response in static_headers helper

- src/kemal.cr
> use Process.on_terminate to support SIGTERM termination.

- spec/exception_handler_spec.cr
- spec/helpers_spec.cr
Hi!
Thank you for the great Kemal project.
In the AI coding era, I think more people will need simple web apps that work on low-resource servers.
Kemal is a good fit for that. I wanted to contribute something, so I used the [typos](https://github.com/crate-ci/typos) tool to find some typos.
- spec/exception_handler_spec.cr: "occured" → "occurred"
- spec/helpers_spec.cr: "disble" → "disable"
There are no alternative designs. 
Improves documentation.
None. This is a simple spelling correction with no functional changes.
> Fix typos in spec files
