kemalcr/kemal

- spec/param_parser_spec.cr
- src/kemal/param_parser.cr
This PR ensures, that body params are parsed only when needed.
/cc @sdogruyol
> Parse request body params only if content type is incorrect

- spec/param_parser_spec.cr
- src/kemal/param_parser.cr
Heya, toying around with this, and ran into an error when GETting an application/json route with no request body. This PR adds support for that.
> application/json GETs can have no request body

- spec/kemal_handler_spec.cr
- src/kemal/param_parser.cr
- src/kemal/request.cr
- src/kemal/route.cr
Following are the changes made in this commit:
- Added support for magic param `_method` just like Rails, Sinatra
etc.. Browsers which don't support `PUT`, `PATCH` and `DELETE` methods
can simulate them by sending `method` param in request body.
- The default Content-Type to parse request body submitted via forms
etc. is `application/x-www-form-urlencoded`. But if we send Ajax
request in Chrome ($.post) then by-default Content-Type is set to
`application/x-www-form-urlencoded; charset utf-8` which was not
getting matched. I changed the code from `==` to match against a
regular expression using `=~`.
- Print name and color of overridden HTTP method via Logger instead of
printing name and color or request's incoming HTTP method.
> Added support for magic param `_method` just like Rails, Sinatra.

- spec/kemal_handler_spec.cr
- src/kemal/handler.cr
First I tried implementing this solution in such a way that it
explicitly clears body and set `Content-Length` header to body's size.
But for some reason, if I call the URL from cURL then `Content-Length`
header was blank which defeats the very purpose of `HEAD` requests.
I then later anticipated that since `HEAD` would be by-default
implemented by `HTTP::Server` module, there is no need to explicit
clears body and setting `Content-Length` but the way we have written
our previous specs were returning body as well. We could have used some
TestServer kind of thing but if we go to that route we explicitly need
to test non-existent route which I thought would create some
inconsistency among specs.
Crystal has clearly written specs for HEAD requests to make sure body
is not read for them. See …
> Implemented HTTP `HEAD` method.

- README.md
- docs/README.md
- docs/views.md
- spec/asset/hello.ecr
- spec/view_spec.cr
- src/kemal/view.cr
To have dynamic rendering mechanism, I created a shortcut to the ECR parser. It actually binds built-in ECR parser to the Kemal as a macro.
DONE
```crystal
get "/:name" do |env|
render "hello.html"
end
```
TODO
```crystal
get "/:name" do |env|
render "hello <%= env.params["name"] %>"
end
```
> Add render macro to kemal core.

- README.md
- spec/kemal_handler_spec.cr
- src/kemal.cr
- src/kemal/config.cr
- src/kemal/context.cr
- src/kemal/macros.cr
- src/kemal/route.cr
- src/kemal/view.cr
Removed `env.redirect` in-favor of `redirect` in-order to make Kemal's
API look more like Sinatra.
Thanks @sdogruyol and @f for introducing me to macros :-).
> Removed env from redirect and changed redirect from method to macro.

- src/kemal.cr
- src/kemal/config.cr
- src/kemal/param_parser.cr
Hi! because I was testing kemal in crystal 0.10.0, this PR changes `Dir.working_directory` to `Dir.current`
This is a breaking change.
https://github.com/manastech/crystal/releases/tag/0.10.0
> Make compatyble with crystal 0.10.0

- docs/getting_started.md
Otherwise the following error will be shown:
`Syntax error in ... unterminated char literal, use double quotes for strings`
Tested with crystal --version
Crystal 0.10.0 (Wed Dec 23 21:19:16 UTC 2015)
This error is corrected in the example below showing the complete file.
> docs: string require double quotes

- src/kemal/route.cr
Right now every `match?` performed against the routes defined result
in a new Regex compiled for the exact same `@path`.
Since `@path` of the Route does not change on every request, we
pre-build it to avoid repeated allocations.
When testing this in release mode (against `0.10.2 [d1e3f0b]`):
```
Before: 32408.48 req/s
After: 34862.07 req/s
```
Cheers.
> Build Route Regex once to reduce allocations

- src/kemal/handler.cr
- src/kemal/param_parser.cr
- src/kemal/route.cr
It's a total performance boost:
**Before:**
```
Requests/sec:  77267.30
Latency: 522.23us
```
**After:**
```
Requests/sec:  84340.61
Latency: 474.51us
```
🚀🚀🚀
> Radix-tree already has url param parsing with state-machine implementation which is faster than regex parsing. We don't need regex parsing anymore.

- spec/route_handler_spec.cr
- src/kemal/context.cr
`301` means "Moved Permanently", so browser caches this redirect, it is used when changing server URL.
`302` means "Found", it is used generally (e.g. redirect top page after login).
Each of `301`, `302`, `303` and `307` means redict, but they are different. We could choice those status in case.
> Use 302 to redirect instead of 301

- src/kemal/middleware/filters.cr
- `add_filters` no longer needs to be called explicitly it will be lazily called if needed.
- the Filter middleware no longer needs to be the first in the handlers array.
- `before` and `after` methods will raise an exception if a filter for the requested path is already defined.
> Fix filter middleware

- _docs/views.md
Add missing ```|env|``` to the get-loop.
> Fix undefined variable env error in example code.

- _docs/views.md
The views folder should be in the src directory and that should be reflected
in the example path aswell.
Closes sdogruyol/kemal/issues/88
> Change view path to be a subfolder of src.

- spec/route_handler_spec.cr
- src/kemal.cr
- src/kemal/common_error_handler.cr
- src/kemal/config.cr
- src/kemal/exceptions.cr
- src/kemal/route_handler.cr
Hi,
While playing with my logger I realized that the error handling wasn't very flexible, so I tried to decouple it from the RouteHandler.
Now a custom logger will receive exceptions messages and we'll be able to provide a custom `ErrorHandler`.
Also I don't understand well how the spec works so for now 2 tests are failing:
- `spec/route_handler.cr L111`: Kemal::RouteHandler renders 404 on not found
- `spec/route_handler.cr L191`: Kemal::RouteHandler can't process HTTP HEAD requests for undefined GET routes
But when I try it with a live instance everything works the same.
Here are all the changes I made:
config.cr:
- changed `setup_logging` to only instantiate and add the CommonLogger to the handlers if no logger has already been instantiated.
That way the CommonLogger is no longer added …
> decoupled errors from route-handler

- src/kemal/common_error_handler.cr
Sorry I made a small mistake in the previous PR.
I didn't realize `to_s` also serialized the `message`, before this it would print like:
`Exception: Requested path: 'GET:/a' was not found.: Requested path: 'GET:/a' was not found.`
instead of
`Exception: Requested path: 'GET:/a' was not found.`
> fixed small redundancy.

- shard.yml
- src/kemal/helpers.cr
This will allow people to use other template languages (supported by Kilt) without creating different macros.
For instance, if one wanted to use Slang, they'd have to do something like:
```crystal
macro render_slang(filename)
__view__ = String::Builder.new
embed_slang({{filename}}, "__view__")
__view__.to_s
end
```
and then probably write an equivalent one for rendering with a layout.
With this change, no extra code is necessary except for `require "slang"` somewhere.
I know adding dependencies is not something to take lightly, but I think, given the lightweight-ness of Kilt and the minimal changes required to make it work, it's worth considering
> Abstract template engines with Kilt

- src/kemal.cr
- src/kemal/config.cr
- src/kemal/helpers.cr
Hello
Since I plan to only use Kemal for a JSON API I tried to see what would happen if I removed the `StaticFileHandler` (because if there was no overhead there would be no point making it optional).
Here are the results:
With the `StaticFileHandler`:
```
➜  kemal-api git:(master) ✗ crystal build --release src/kemal-api.cr && ./kemal-api
[development] Kemal is ready to lead at http://0.0.0.0:3000
2016-02-15 07:45:01 +0100 | 200 | GET /lol/a - 1.06ms
2016-02-15 07:45:06 +0100 | 200 | GET /lol/a - 41µs
2016-02-15 07:45:14 +0100 | 200 | GET /lol/a - 44µs
2016-02-15 07:45:17 +0100 | 200 | GET /lol/a - 70µs
2016-02-15 07:45:20 +0100 | 200 | GET /lol/a - 63µs
2016-02-15 07:45:22 +0100 | 200 | GET /lol/a - 70µs
2016-02-15 07:45:24 +0100 | 200 | GET /lol/a - 49µs
```
That's really fast and great …
> Make having StaticFileHandler optional

- README.md
- src/kemal/helpers.cr
Since Kilt >= 0.2 (now v0.3.0), there's a simpler `Kilt.render` method to embed to a String directly.
Also, some templating engines take other arguments therefore that's now possible with the args splat.
I've added a mention in the README so that people understand a little better why the kilt dependency.
> use new Kilt >= 0.2 syntax, add mention in readme for clarity

- spec/context_spec.cr
- spec/middleware/filters_spec.cr
- spec/param_parser_spec.cr
- spec/route_handler_spec.cr
- spec/route_spec.cr
- spec/spec_helper.cr
- spec/view_spec.cr
- src/kemal/context.cr
- src/kemal/middleware/filters.cr
- src/kemal/param_parser.cr
- src/kemal/request.cr
- src/kemal/route.cr
- src/kemal/route_handler.cr
I closed #96 and made this one because I forgot to make my changes on a separate branch.
Anyway here's the changelog:
param_parser.cr:
- `@route` parameter was never unused.
context.cr:
- changed `ParamParser.new` accordingly
- added new `route_defined?` method, will be useful for other middlewares, also it’s lazily evaluated only once, so it can be called many times without any performances penalty.
route.cr:
- both class methods didn’t really belong here in the first place, moved them to request.cr
request.cr: 
- there’s no need to call `check_for_override!` it’s now lazily called when you access `.override_method` on `request`
- calling many times `override_method` does not result in many wasted checks anymore (other middlewares will want to know the `override_method` before the …
> added verb for filters and minor improvements

- spec/middleware/filters_spec.cr
- src/kemal/middleware/filters.cr
@jeromegn pointed out to me in #105 that people might want to call many times `before_x` or `after_x` so I updated the filter, it no longer raises an exception if there's already one filter for this verb/path.
And now calls all the blocks in the order they were defined.
Also I'll make it clear in the docs but these convenience methods should __not__ be used by plugins/addons, instead they should do all their work in their own middleware.
PS: this time I ran `crystal tool format` should look better than the previous PR :smile:
> Ability to add many blocks per route filter

- _docs/filters.md
Forgot to add the warning yesterday.
Also fixed the formatting and changed back the `'''crystal` to `'''ruby` to get the colored syntax.
> Forgot important warning.

- src/kemal/context.cr
- src/kemal/param_parser.cr
- src/kemal/route_handler.cr
Hi :smile: 
I realized some middlewares will want to have access to the params, and most of them are already available in `context.params` but they wouldn't get the `urlparams` because `request.url_params` was set in the `RouteHandler`.
Now the url_params are lazily set and parsed when `params` is accessed on the context (therefore accessible to all the middlewares).
(This is a 2 lines change).
Also I made the `parse_url_params` last so they don't get overwritten by params in the body.
> Decoupled urlparams from routehandler.

- src/kemal/dsl.cr
As in https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.2 and because it's a nice way to document API
> Add options to the DSL

- src/kemal/config.cr
- src/kemal/view.cr
The logger and errors middleware should always be first and second, so that if I have a custom error handler middleware I can make it rescue anything even an exception that would be raised by another middleware. 
Same for the logger, since it logs the time it takes to process a request it makes sense that it's the first called.
Also added 2 views that I needed for parameters validation `render_400` and `render_415`.
> Set positions for errors and logger middleware, added 2 views

- spec/param_parser_spec.cr
- spec/route_handler_spec.cr
- spec/view_spec.cr
- src/kemal.cr
- src/kemal/context.cr
- src/kemal/param_parser.cr
- src/kemal/request.cr
It now decouples `env.params` to `env.params.query`, `env.params.body`,
`env.params.json` and `env.params.url` and you still can access merged
values using `env.params.all`
> Upgrade ParamParser to make it more convinient.

- src/kemal/common_error_handler.cr
- src/kemal/view.cr
`Exception#to_s` is actually showing `Exception#message` and nothing else (https://github.com/crystal-lang/crystal/blob/60777f31ea84f8fd627bfec448ac86bd6221c161/src/exception.cr#L148)
- Converted it to `Exception#inspect_with_backtrace` (https://github.com/crystal-lang/crystal/blob/60777f31ea84f8fd627bfec448ac86bd6221c161/src/exception.cr#L160) to see. Put `:red` logs to the STDOUT via logger.
- Styled the backtrace in the HTML view.
> Show backtrace in 500 statuses using `inspect_with_backtrace`

- src/kemal.cr
Hi,
I tried playing around with kemal today and this was breaking the example app. I see it's breaking the tests on current kemal master too. I honestly have no idea what I'm doing but it fixed the issue!
> Don't convert host_binding to slice when instantiating server

- spec/helpers_spec.cr
- spec/route_handler_spec.cr
- src/kemal/helpers.cr
Today with @askn we needed to return the block in the middle of the
code with a simple return but it was kinda tricky, needed to write
3 lines of code with next statement.
It may be easier to use a simple `return_with` macro.
```crystal
get "/" do
if env.query["not_found"] == "1"
return_with env, 404, "Not Found"
end
"hello world"
end
```
In this case, the server will response as "404: Not Found" in the case of `?not_found=1`
querystring is passed.
> Added return_with macro to break response blocks.

- _docs/middlewares.md
- The `logger` macro doesn't exist anymore
- Need to pass the `Kemal.config.env` to the logger initialize
> Update docs for the custom logger

- spec/common_exception_handler_spec.cr
- src/kemal.cr
- src/kemal/common_exception_handler.cr
- src/kemal/config.cr
- src/kemal/dsl.cr
- src/kemal/exceptions.cr
- src/kemal/route_handler.cr
- src/kemal/view.cr
This PR adds custom error handlers to Kemal.
An example
```
error 403 do |env|
"You shall not pass"
end
```
> Custom Error handlers

- src/kemal.cr
- src/kemal/common_exception_handler.cr
- src/kemal/view.cr
This allows the user to customize to 404 error handler like
```crystal
error 404 do |env|
env.response.content_type = "application/json"
{code: 404, message: "Not Found"}.to_json
end
```
> Allow 404 error handler to be customizable

- _docs/views.md
Since Ruby doesn't know about macros, the filename variable is lost in the html output.
> Fix bad highlighting

- _docs/views.md
Because it totally confused me on http://kemalcr.com/docs/views/, displayed as `render "my/app/view/base/path/#}.ecr",` if you don't use the `raw`. Liquid issue.
> fix display of triple braces

- spec/middleware/http_basic_auth_spec.cr
- spec/param_parser_spec.cr
- spec/route_handler_spec.cr
- spec/websocket_handler_spec.cr
- src/kemal.cr
- src/kemal/cli.cr
- src/kemal/config.cr
- src/kemal/middleware/ssl.cr
Tuple literals are now declared with the old syntax for hash literals, breaking several specs. SSL has also been moved around a bit and renamed.
> Fix SSL and specs for 0.18

- spec/helpers_spec.cr
- src/kemal/helpers.cr
I was working on cloning a Sinatra app and it seemed like it had a much easier way to add multiple headers, so I thought it may be useful to have a similar syntax for Kemal. I also had trouble using the [example](http://kemalcr.com/docs/http-requests/) to add headers and had to do `env.response.headers.add("foo", "bar")` which was annoying.
Let me know if any of these PRs should be opened against a branch other than master for tagging/versioning purposes.
> Add headers helper method

- spec/session_spec.cr
- src/kemal.cr
- src/kemal/context.cr
- src/kemal/session.cr
Sessions are stored in a non-persistent Hash.  Only String values are allowed.  A reaper fiber regularly removes any sessions which expire due to inactivity.
See also #91.
> Implement basic in-memory session store

- spec/middleware/csrf_spec.cr
- src/kemal/middleware/csrf.cr
This adds a middleware which, when activated, will deny any form submission which does not include a valid `authenticity_token` parameter or `http-x-csrf-token` header with the request.
If you're not aware of CSRF, it's a common security hole for sites. https://en.wikipedia.org/wiki/Cross-site_request_forgery
The header and parameter names are identical to the ones supported by Ruby's [rack-protection](https://github.com/sinatra/rack-protection/blob/master/lib/rack/protection/authenticity_token.rb) gem for interoperability purposes.
> Implement CSRF protection

- spec/config_spec.cr
- src/kemal/cli.cr
- src/kemal/config.cr
This commit adds the ability to add a closure suitable for adding
additional options. It is expected to allow someone to set global,
module or class level variables so they can pass changes/options
suitable for making decisions.
Solves #129 
I've tried multiple names (additional_options, additional_opts_func, on, ...) and the only one that seems unambiguous is `on_options`.
I wonder if Kemal::Config is a good place to put it. I've noticed that other pieces for configuration land there and it seems strange to land option configuration in Kemal::CLI when the rest of the application options are stuffed into Kemal::Config.
Thoughts?
> Support additional options as part of the Config

- README.md
- _docs/context.md
I've also added a simple `README.md` to the branch for others to be able to help contribute. The headers doc just removes `add_header` and replaces it with `env.response.headers`. Let me know if I need to make any other changes here.
> Fixing docs on adding headers

- src/kemal/helpers/helpers.cr
This effectively overrides `Content-Type` header key instead of adding another one, what you can see on the screenshot below:
> Override `Content-Type` header key in send_file helper

- src/kemal/helpers/helpers.cr
It proves quite helpful when dealing with memory backed or remote resources since you don't have a physical file location you can provide.
Also, Thanks for making this library, it's a fun to use :)
> Add send_file helper variation for sending raw data

- spec/param_parser_spec.cr
- src/kemal/param_parser.cr
Resolves case when `Content-Type` header is passed in form of `application/json; charset=utf-8`.
> Fix parsing JSON params when "charset" is present in "Content-Type" header

- src/kemal/param_parser.cr
It shows real intention and covers cases when `application/json` is passed in the middle of the string, like `some_garbage_string; application/json`
> Use String#starts_with? instead of String#[]?

- src/kemal.cr
- src/kemal/cli.cr
- src/kemal/config.cr
Compilation fails with `-D without_openssl`
```shell
% crystal build --release --link-flags "-static" -D without_openssl sample.cr
Error in ./sample.cr:1: while requiring "./src/kemal"
require "./src/kemal"
^
in ./src/kemal.cr:2: while requiring "./kemal/*"
require "./kemal/*"
^
in ./src/kemal/config.cr:11: undefined constant OpenSSL::SSL::Context::Server
@ssl : OpenSSL::SSL::Context::Server?
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
(tested on crystal-0.19.1)
We use `-D without_openssl`
- 1. when we compile codes statically on ubuntu-16.04 where it seems `libcrypto.a` is miss packaged.
- further discussion: https://github.com/crystal-lang/crystal/issues/3182
- 2. when we need small static binary
- For example: a binary size of statically compiled kemal app is
- 6.3MB (default)
- 3.8MB (without …
> Disable ssl when `-D without_openssl` is given

- src/kemal.cr
Simply adding the possibility to choose the port to listen on.
Permitting `Kemal.run(8080)` for example
and of course keep compatibility with `Kemal.run`
> Adding port to Kemal#run

- spec/config_spec.cr
- spec/middleware/csrf_spec.cr
- spec/session_spec.cr
- src/kemal/config.cr
- src/kemal/session.cr
Makes session support the following types
- String
- Int64
- Float64
- Bool
Make session name and expire_time configurable.
```crystal
Kemal.config.session["name"] = "kemal"
Kemal.config.session["expire_time"] = 1.hours
```
//cc @mperham
> Improve session support

- README.md
Small fix for markdown rendering in crystal-docs.org
> Add new line between logo and title

- src/kemal/static_file_handler.cr
The content-type currently defaults to text/html, which is inaccurate
because no content is being returned. Google, along with popular CDNs,
omit the Content-Type header for 304 response.
> Remove Content-Type response header if the file is cached

- src/kemal/helpers/helpers.cr
Thanks @miguelm on https://github.com/sdogruyol/kemal/pull/223.
Instead of just yielding `|field, data|` on `parse_multipart` we are going to yield a `UploadFile` object which has `field`,`data`, `meta`, `headers` properties.
```crystal
post "/upload" do |env|
parse_multipart(env) do |f|
image1 = f.data if f.field == "image1"
image2 = f.data if f.field == "image2"
puts f.meta
puts f.headers
"Upload complete"
end
end
```
> Improve Multipart upload information

- spec/param_parser_spec.cr
- src/kemal/dsl.cr
- src/kemal/param_parser.cr
I found a little url parameter issue. In some other comparable non-crystal web frameworks, url parameters are decoded.
Here is an example comparing the response of ruby's sinatra with kemal.
```ruby
get "/user/:email" do
params["email"]
end
```
```ruby
get "/user/:email" do |env|
env.params.url["email"]
end
```
Sinatra correctly decodes the url parameters. I have not used Sinatra in production, but I have a good amount of experience with the Node.js Express framework and I know that the url parameters are also decoded with Express.
Keep up the good work! 👍
> Decodes url parameters

- src/kemal/param_parser.cr
Sorry for the quick fix after recently merging the other PR. I was reading through the API docs and discovered a more appropriate method for decoding URL params. 
I ran the specs and everything works as expected. Sorry 😓
> Replace implementation with more appropriate URI.unescape

- spec/context_spec.cr
- spec/handler_spec.cr
- spec/helpers_spec.cr
- spec/spec_helper.cr
- src/kemal/config.cr
- src/kemal/middleware/filters.cr
- src/kemal/route.cr
This improves middleware ordering.
Middlewares should work as intended, before all before_* filters and routes.
```
Request -> Middleware -> Filter -> Route
```
This works but `crystal spec` fails with a weird issue.
```
crystal spec
F...........................................................................
Failures:
1) Handler adds custom handler before before_*
Failure/Error: client_response.body.should eq("Kemal is so Great")
expected: "Kemal is so Great"
got: "Kemal Great"
```
Meanwhile requiring the spec files with exact paths work.
```
crystal spec spec/handler_spec.cr spec/middleware/filters_spec.cr spec/middleware/csrf_spec.cr spec/middleware/http_basic_auth_spec.cr spec/common_exception_handler_spec.cr spec/common_log_handler_spec.cr spec/config_spec.cr spec/context_spec.cr …
```
> Middleware ordering

- _docs/sessions.md
This updates the docs with information from commits 6d4bf57 and 8c600cb, which add more data types to session and allows for configuring the session TTL.
> update session docs with TTL and available types

- src/kemal/helpers/macros.cr
When using `halt` (`return_with`), the response body is not closed and can still be written to.
Example
```ruby
error 403 do
"Access Forbidden!"
end
get "/" do |env|
halt env, 403, "Access Denied"
end
```
Hitting the base `/` path would return `"Access DeniedAccess Forbidden!"`. By closing the response, the response body and status code cannot be changed. I am assuming that this is expected behavior when using `halt`.
When doing `env.response.close` the response IO would be closed and the body would be `"Access Denied"`, as expected.
The 403 error block will still run, but any new information attempting to append to the response will be ignored.
> Close repsonse on halt

- spec/handler_spec.cr
- src/kemal.cr
- src/kemal/ext/handler.cr
This is alternative implementation for `only` and `exclude` paths for a middleware.
This PR requires that from now on all middlewares must inherit from `Kemal::Handler`.
We use the `only/exclude`  macro to define which routes to take action. 
```crystal
class OnlyHandler < Kemal::Handler
only ["/only"]
def call(env)
super && return(call_next(env))
env.response.print "Only"
call_next env
end
end
```
And to explicitly check & return the matching paths `super && return(call_next(env))` must be implemented.
This has really low performance penalty compared to https://github.com/sdogruyol/kemal/pull/244. This approach is more than %50 faster.
//cc @samueleaton @askn @f
> Only / Exclude Paths in Middleware

- shard.yml
Radix project follows a Semantic Versioning approach which avoids introducing breaking changes in PATCH releases.
With this in consideration, it is safe to use pessimistic operator to indicate the version of Radix to use.
Closes #261
> Update Radix to latest and lock pessimistically

- _docs/getting_started.md
The official documentation of crystal also uses https to load the setup script. Using http alone is way too unsecure.
> Use https for loading crystal setup script

- spec/run_spec.cr
- src/kemal.cr
Allow `kemal.run` to optionally take a code block to change the post-start logging, or run any other post-start code at that time. This fixes part of #290, wasn't sure how to handle the shut-down text.
I hope I'm not missing some glaringly obvious configuration here that already allows for this!
> Add configurable startup logging as a block

- spec/config_spec.cr
- src/kemal.cr
- src/kemal/config.cr
By default, it is still on, but config.shutdown_message can toggle it off:
```crystal
Kemal.config.shutdown_message false
```
> Allow for disabling the shutdown message

- src/kemal/file_upload.cr
- src/kemal/helpers/helpers.cr
- src/kemal/param_parser.cr
- src/kemal/route_handler.cr
This makes file upload easier to handle. Thanks @crisward for giving me the idea 🙏 
I made some small modification to his PR #305 for this.
```crystal
post "/upload" do |env|
file = env.params.files["image1"].tmpfile
file_path = ::File.join [Kemal.config.public_folder, "uploads/", file.filename]
File.open(file_path, "w") do |f|
IO.copy(file, f)
end
"Upload ok"
end
```
With this you can access the underlying upload file with `env.params.files["upload_key"].tmpfile`.
There's also other properties as
- filename
- tmpfile_path
- meta
- headers
> Make file upload accesible from context.

- src/kemal/dsl.cr
- src/kemal/helpers/utils.cr
This PR changes the name of `Kemal::Utils::path_starts_with_backslash` to `Kemal::Utils::path_starts_with_slash` for technical correctness reasons.
See also:
https://en.wikipedia.org/wiki/Slash_(punctuation)
https://en.wikipedia.org/wiki/Backslash
> path_starts_with... method naming

- src/kemal.cr
- src/kemal/common_exception_handler.cr
This PR fixes regression introduced in 1afb4cbfa8218ab8616c59a041dcc85fa72834a8, where `log` helper came into the being.
> Remove extraneous newline characters passed to log helper

- src/kemal/param_parser.cr
This PR makes sure that every file returned by `ParamParser` will have its `#size` set.
Fixes #309.
> Skip files with empty #size in ParamParser

- spec/helpers_spec.cr
- src/kemal/helpers/helpers.cr
send_file was returning file size, if you use it as the last command in a route, it would append file size to the end of the output.
not sure about other send_file, haven't tried.
> Prevent send_file returning filesize

- spec/context_spec.cr
- spec/spec_helper.cr
- src/kemal/ext/context.cr
- src/kemal/helpers/macros.cr
- src/kemal/param_parser.cr
Here's my use case. The problem I'm having is that in middleware, filters or between methods, I want to store an object and not necessarily a base type. When I want an object, I end up polluting the `HTTP::Server::Context` class. I'd much prefer to be able to store the object in context storage. 
Here's a contrived example:
```crystal
class MyType
property name
@name = "kemal"
end
HTTP::Server::Context.add_store_type(MyType)
before_get "/" do |env|
t = MyType.new
t.name = "awesome"
env.set "my_type", t
end
get "/" do |env|
t = env.get("my_type").as(MyType)
t.name
end
```
> User defined context store types

- src/kemal/helpers/helpers.cr
security header for older browsers to prevent content sniffing
> X-Content-Type-Options = "nosniff" #379

- spec/handler_spec.cr
- src/kemal/handler.cr
Without parens, the macro is expanded to 
```
2.     ["/one", "/two"] of ::String.each do |path|
3.       @@exclude_routes_tree.add "#{class_name}/#{"GET".downcase}#{path}", "/#{"GET".downcase}#{path}"
4.     end
5.
```
which is a syntax error
> allow %w in Handler macros

- spec/context_spec.cr
- spec/middleware/filters_spec.cr
- spec/param_parser_spec.cr
- spec/spec_helper.cr
- spec/websocket_handler_spec.cr
- src/kemal/dsl.cr
- src/kemal/ext/context.cr
- src/kemal/route_handler.cr
- src/kemal/websocket_handler.cr
This fixes https://github.com/kemalcr/kemal/issues/349 and simplifies using WebSockets with named url parameters.
With this PR one can do
```crystal
ws "/:room_name" do |socket, env|
env.params.url["room_name"]
end
```
> Add context to WebSocket

- spec/static/dir/index.html
- spec/static_file_handler_spec.cr
- src/kemal/config.cr
- src/kemal/helpers/helpers.cr
This PR adds support for customizing the headers of built-in `Kemal::StaticFileHandler`. Useful for supporting `CORS` 👍 
```crystal
static_headers do |response, filepath, filestat|
if filepath =~ /\.html$/
response.headers.add("Access-Control-Allow-Origin", "*")
end
response.headers.add("Content-Size", filestat.size.to_s)
end
end
```
Based on #228, fixes https://github.com/kemalcr/kemal/issues/233
> Allow headers in built-in static file server

- src/kemal/ext/context.cr
Fixes compile error "undefined constant Route"
> Set correct namespace for Route

- src/kemal/helpers/helpers.cr
Video doesn't work in safari.
It seem to be to do with the content-range header. Safari initially asked for the first byte. 
However with a single byte request, the header outputs
`bytes 0-0/1000` (if this file is 1000 bytes in size)
It does work however if we make the end value 1. But removing the `-1` it breaks it in chrome. So I suggest this change, which means the end can't be smaller than 1.
> Fix for video in safari

- src/kemal/helpers/helpers.cr
There's only one minor breaking change
- Use Flate::Writer.new is now Flate::Writer.open
> Crystal Next Support

- README.md
"Middlewares" is not a word. See: gin-gonic/gin#252.
> Change "middlewares" to "middleware"

- README.md
[Getting Started](http://kemalcr.com/guide/) in Kemal's official document is clear. Commands from installation of Crsytal-lang to application creation are not omitted. I added a link to Getting Started into Installation.
> Improve Installation in README

- spec/websocket_handler_spec.cr
- src/kemal.cr
I've notice the following needed changes for the upcoming crystal version.
This changes are not compatible with 0.24
Related to:
* crystal-lang/crystal#5776
* crystal-lang/crystal#6027
> Updates to upcoming Crystal 0.25.0

- spec/config_spec.cr
- src/kemal/config.cr
PR to make `crystal spec` run with default value for the case requires it. 
On my local, `~/Workspace/kemal$ crystal spec` failed because of;
```
Failures:
1) Config sets default powered_by_header to true
Failure/Error: Kemal.config.powered_by_header.should be_true
Expected: true
got: false
Finished in 7.76 milliseconds
103 examples, 1 failures, 0 errors, 0 pending
Failed examples:
crystal spec spec/config_spec.cr:20 # Config sets default powered_by_header to true
```
I found `"does not initialize context with X-Powered-By: Kemal if disabled"` in init_handler_spec.cr runs before the above test.  
And it set `Kemal.config.powered_by_header = false` in shared `Kemal::Config::INSTANCE`.  
(`Kemal::Config::INSTANCE` is constant so it will be shared if test cases access config with …
> reset values to test with default value

- spec/run_spec.cr
- src/kemal.cr
Fixes  #459 
This allows the config block passed to `Kemal.run` to apply custom bindings to `config.server` using the new `HTTP::Server` API from Crystal 0.25.0. `Kemal.run` will only call default `server.bind_tcp(config.host_binding, config.port)` if the server was not already bound in the config block. Multiple listen interfaces are also supported (including Unix sockets) and will show in the startup log message.
In order to properly spec the behavoiour of `Kemal.run` it needs to be compiled separately, in a new process to avoid sharing global state.
> Refactor `Kemal.run` to allow custom port binding

- spec/static_file_handler_spec.cr
- src/kemal/static_file_handler.cr
Previous history: https://github.com/kemalcr/kemal/pull/440 + https://github.com/crystal-lang/crystal/pull/6145
We can now remove some code and all the tests should still pass (added one extra assertion just to be sure)
Stdlib should probably refactor whole `unless context.request.method`
block a little bit as well for more re-usability, but that's for the future
Alternative approach in #440 was presented and rejected ;)
Relying on stdlib instead of duplicating own logic.
Crystal 0.25.1+ as requirement - which is not something authors might want now 🤔
> Remove etag logic as it's not implemented in Crystal 0.25.1

- spec/config_spec.cr
- src/kemal/config.cr
I want to be able to specify the Kemal version in apps I create using something like Kemal::VERSION. Assuming that shard.yml always contains the latest version number, I propose a line similar to the following in a Kemal module:
``` 
VERSION = {{ `shards version #{__DIR__}`.chomp.stringify }}
```
I suppose a literal version number could be used,`VERSION = "0.23.0"`, but that would mean having to update the version in at least two places.
The benefits are purely cosmetic, at least for me.
1. `shards version` changes
2. shard.yml not updated (not likely!)
3. an update removes the version macro
> add a VERSION constant

- src/kemal.cr
`require "tempfile"` was left over after #465 but is not used anymore.
This PR removes it which makes Kemal compile with both Crystal 0.26.1 and current master (where `Tempfile` has been removed).
> Remove unused require "tempfile"

- src/kemal.cr
Closes #494
`.bind_ssl` was removed[0] from crystal-lang, use `.bind_tls` instead
- `[0]` crystal-lang/crystal#6699
> Remove deprecated alias HTTP::Server#bind_ssl

- spec/override_method_handler_spec.cr
- src/kemal/override_method_handler.cr
This adds `Kemal::OverrideMethodHandler` as a Kemal middleware to handle `_method` magic param in the `POST` request body. Fixes #486 
This is not in the default Kemal handlers. 
You can enable via:
```
add_handler Kemal::OverrideMethodHandler::INSTANCE
```
> Add Kemal::OverrideMethodHandler to support _method magic param

- src/kemal/file_upload.cr
- src/kemal/param_parser.cr
Fixes #496 and adds back `env.params.files` with caching.
P.S: This is targeted for Crystal 0.27.0
> Fix multipart upload

- src/kemal/param_parser.cr
Without these changes, the following code will not work:
```crystal
post "/upload" do |env|
file = env.params.files["file"].tempfile
File.open(file.path, "w") do |f|
IO.copy(file, f)
end
"Upload OK - #{file.path}"
end
```
`env.params.files` will always be an empty hash
> fix env.params.files

- src/kemal/handler.cr
After #487 some variables were missing in `macro exclude`, I'm just adding the variables, a copy paste from` macro only`
No error while using exclude
> Fixing exclude method in Handler

- spec/helpers_spec.cr
- src/kemal/helpers/helpers.cr
if the disposition type matches "attachment", this
indicates that the recipient should prompt the user to save the response
locally, rather than process it normally.
Without proposed changes it can be done like this:
```crystal
get "/download" do |env|
env.response.headers.add("Content-Disposition", "attachment; filename=\"image.jpg\"")
send_file env, "./asset/image.jpeg"
end
```
With this changes:
```crystal
get "/download" do |env|
send_file env, "./asset/image.jpeg", filename: "image.jpg"
end
```
> allow to set filename for send_file

- shard.yml
SSIA, see https://github.com/crystal-lang/shards/blob/a2a5e7990ab9a234bea8fbcaea521cc98513607f/SPEC.md#authors
> Fix misspelled `authors` key in shard.yml

- shard.yml
This reverts commit ff37027afeb501a6a3461aceb21ec044dd1c24a3.
There's no point in having it defined.
> Revert "Add targets to shard.yml"

- shard.yml
I've just noticed there's a `license` key missing in `shard.yml`. This PR fixes that.
> Specify license in shard.yml

- src/kemal/log_handler.cr
Citing from the crystal docs 
```
When Time.now is called multiple times, the difference between the 
returned instances is not guranteed to equal to the time elapsed between
making the calls; even the order of the returned Time instances might 
not reflect invocation order.
```
This is what happens in the base log handler. This uses `Time.monotonic` instead.
Disadvantage of this implementation: We have an additional call of `Time.now` to find out the current date for logging purposes. Maybe that was the reason this has not been implemented. if that is the case, feel free to close.
> Properly measure request time using Time.monotonic

- .travis.yml
- shard.yml
- src/kemal/exception_handler.cr
- src/kemal/ext/response.cr
- src/kemal/static_file_handler.cr
> Use Ameba on Travis CI

- src/kemal/param_parser.cr
- src/kemal/static_file_handler.cr
A `Crystal::VERSION` check should be added if you want kemal to be warning free but also keep working in 0.29.0.
You can double check in https://github.com/crystal-lang/crystal/pull/7997 which encode/decode method apply better for each situation.
> Upgrade to Crystal v0.30.0

- src/kemal/helpers/helpers.cr
```crystal
Kemal.run
```
Serving a file > ~2.1 GB, for example:
```
$ dd if=/dev/urandom of=file2 bs=1000 count=2147484 status=progress
```
Request with:
```
$ curl http://localhost:3000/file2 -H 'Range: bytes=0-' -v -o /dev/null
```
which produces:
```
Exception: Negative limit (ArgumentError)
from /usr/lib/crystal/io.cr:1147:5 in 'copy'
from /helpers.cr:218:5 in 'multipart'
from src/kemal/helpers/helpers.cr:137:12 in 'send_file'
from src/kemal/static_file_handler.cr:65:9 in 'call'
from /usr/lib/crystal/http/server/handler.cr:26:7 in 'call_next'
from src/kemal/exception_handler.cr:8:7 in 'call'
from /usr/lib/crystal/http/server/handler.cr:26:7 in 'call_next'
from src/kemal/log_handler.cr:8:37 in 'call'
from /usr/lib/crystal/http/server/handler.cr:26:7 in 'call_next'
from …
```
> Fix static file handler for range requests on files > 2^31 bytes

- src/kemal/cli.cr
- src/kemal/config.cr
This PR intends to simplify working with `Kemal.config.env` property.
As of now this property stays always initialized to `"development"`, regardless of `KEMAL_ENV` env variable setting. It's being set only once `Kemal::CLI` initializes (which happens on server start) - making it impossible to properly use it before.
After this change `KEMAL_ENV` will be read immediately on `Config` init.
> Check for KEMAL_ENV variable already in Config#initialize 

- src/kemal/log_handler.cr
As tittle says, flushes IO buffers whenever a log entry is written.
If the stdout is not a tty, for example if the program is running inside a systemd unit, the buffered log entries would not appear until buffers are full. This change fixes that and for systemd units, the log is immediately visible in the journal.
Constantly flushing could be a performance issue, however, I think for a production environment, most would want to use a proxy or something else for logging.
> flush io buffer after each write to log

- spec/route_handler_spec.cr
- src/kemal/ext/context.cr
Q: HTTP 302 Redirect - is a message-body needed?
A: A body is needed, but it can be empty.
> allow to set optional response body on redirects

- src/kemal/param_parser.cr
This is a small change to avoid warnings on upcoming Crystal 0.34
Before releasing a Crystal 0.34 version probably https://github.com/crystal-ameba/ameba/pull/138 is wanted.
> Comply exhaustive case check

- src/kemal/helpers/helpers.cr
This change explicitly requires dependent code so that transitional types aliases (and deprecation warnings) are included. Paves the way for the release of 0.35.0.
See: https://github.com/crystal-lang/crystal/pull/8886 (specifically the type aliases).
Simply explicitly requires dependent code. When not present, building against the currently nightly crystal build results in errors like the following (including when running the specs):
```
...
...
In src/kemal/helpers/helpers.cr:135:8
135 | File.open(file_path) do |file|
^---
Error: instantiating 'File.class#open(String)'
In src/kemal/helpers/helpers.cr:143:7
143 | Gzip::Writer.open(env.response) do |deflate|
^-----------
Error: undefined constant Gzip::Writer
```
This change does not affect existing functionality, but avoids problems when …
> Pick up Transitional Type Aliases

- spec/route_handler_spec.cr
- src/kemal/ext/response.cr
Fixes https://github.com/kemalcr/kemal/issues/575
This change works for me.
/cc @bcardiff maybe you can provide more information about this issue. Thanks.
> Fix an issues with responding with long strings

- spec/run_spec.cr
Bonus: It also allows run_spec to pass if using bin/crystal wrapper (since the wrapper emits some warnings of `Using compiled compiler at ...`) and that caused the spec to fail without this PR.
> Refactor run_spec to use process exit instead of empty stderr

- shard.yml
Use latest release version of Radix in order to address some of the
routing bugs presented in previous versions of the dependency
See:
- luislavena/radix#23
- luislavena/radix#27
Corrects the bugs experienced in the above issues 😁 
None that I can see from running the specs and a few manual tests.
Radix has been tested against Crystal 0.35.0 through 0.36.1 without issues (Kemal is failing on latest versions, but that is a separate issue).
Cheers,
❤️ ❤️ ❤️
> Use Radix v0.4.0

- shard.yml
With this change is possible to continue development of Kemal in latest version of Crystal (0.36.1).
Without this change is not possible to install Kemal for local development:
```
~/repos/github.com/kemalcr/kemal on  use-latest-ameba [$] via 🔮 v0.36.1
❯ shards install
Resolving dependencies
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/crystal-ameba/ameba.git
Using radix (0.3.9)
Using kilt (0.4.0)
Using exception_page (0.1.4)
Installing ameba (0.12.1)
Postinstall of ameba: make bin && make run_file
Failed postinstall of ameba on make bin && make run_file:
/home/luis/.asdf/installs/crystal/0.36.1/bin/shards build
Dependencies are satisfied
Building: …
```
> Use latest version of Ameba dependency (dev)

- spec/static_file_handler_spec.cr
Change fixes the build failing due to http module now removing ContentEncoding is decompress param is set to true, see also Issue #594
Build should work again now.
No checks are actually performed on the body of the response. But really, this I think was not the spec of the spec
> Fix StaticFileHandler failing spec

- shard.yml
- spec/websocket_handler_spec.cr
- src/kemal.cr
Updating ameba dependency to the latest version.
Stayin' up to date with ameba linter.
`Enumerable#join(separator, &)` might be less performant than its optimized version in `Indexable#join(separator)`, but since the only place that's being changed is the non-critical path I'd consider this as a non-issue.
> Bump ameba dependency to the latest version

- spec/config_spec.cr
- src/kemal.cr
- src/kemal/config.cr
Showing "Kemal" in startup and shutdown messages confuses user
when the static binary is deployed at customer setup.
This PR adds a option to set App name so that it will be shown
when the application starts and shutdown.
Example:
```
get "/" do
"Hello App!"
end
Kemal.config.app_name = "helloapp"
Kemal.run
```
Shows message as follows
```
[development] helloapp is ready to lead at http://0.0.0.0:3000
```
Signed-off-by: Aravinda Vishwanathapura <mail@aravindavk.in>
> New option to set application name

- src/kemal/dsl.cr
Adds array of paths support to before/after filters. With this change you can do
```crystal
before ["/path1", "path2", "path3"], "GET" do 
puts "Doing something for get routes"
end
```
This will reduce code copy/paste. DRY 👍
> Add array of paths support for before/after filters

- shard.yml
Updates [exception_page](https://github.com/crystal-loot/exception_page) shard to ~> 0.2.0
Fixed https://github.com/crystal-loot/exception_page/issues/8
None that I can see.
> Bump exception_page shard to ~> 0.2.0

- spec/helpers_spec.cr
- spec/view_spec.cr
Prevent compile-time problems due to relative paths.
As-is, the specs assume that you're running from the root directory of the project.
It's not a big deal in almost every situation, so feel free to disregard this :)
> Allow running specs from any directory

- spec/middleware/filters_spec.cr
- src/kemal/filter_handler.cr
Code to reproduce:
```
before_all do |env|
puts "BEFORE <"
end
after_all  do |env|
puts "> AFTER"
end
get "/" do
"Hello World!"
end
Kemal.run
```
`after` request will never be executed.
Not sure what going on here. But the origin of the issue is in `radix` shard. It does not properly handle paths without trailing `/`.
```
require "radix"
tree = Radix::Tree(Symbol).new
tree.add "after/ALL/*", :after
tree.add "before/ALL/*", :before
pp tree.find "after/ALL/*"
pp tree.find "before/ALL/*"
```
Output
```
#<Radix::Result(Symbol):0x7fbf3bb8bf00 @key=nil, @params={}, @payload=:after>
#<Radix::Result(Symbol):0x7fbf3bb8bcf0 @key=nil, @params={}, @payload=nil>
```
> fixed executing filters when before and after is defined at the same time

- spec/exception_handler_spec.cr
- src/kemal/helpers/templates.cr
Superseeds #610, thanks @mamantoha 🙏 
Most of the web frameworks (Spring Boot, Rails e.g) do this. With this we do have a common ground with major web frameworks.
None
> Set content type to text/html for 500 exceptions

- src/kemal/helpers/macros.cr
This PR should remove the dependency on Kilt, as suggested in #467.
`Kilt.render` was just an alias for
```crystal
String.build do |io|
ECR.embed({{filename}}, "io", {{*args}}) # => or what ever engine you prefer
end
```
I did try [ECR#render](https://crystal-lang.org/api/1.0.0/ECR.html#render(filename)-macro) but the tests for `content_for` would fail because `ECR#render` (for some reason) didn't see `{{*args}}`.
```crystal
ECR.render({{filename}}, {{*args}}) # => this fails
```
The proposed solution was selected because `ECR#render` is just an alias for the code in the snippet above (- the args).
Should close #467
> Deprecate dependency on kilt

- README.md
- shard.yml
- src/kemal/helpers/macros.cr
This PR removes Kilt and all the reference to it. Fixes #617 
Kemal will now only rely on ECR which is already built-into the Crystal standard library
The users must include and use `Kilt` themsevels
> Remove Kilt

- spec/view_spec.cr
- src/kemal/helpers/macros.cr
Fixes #630 
Turns out that you have to call `ECR.embed` and pass in an `IO::Memory` or it breaks the `content_for` macro.
Tried to update the specs to catch the problems in the future. For the record, the added spec never failed, it was added as a precaution.
> Fix content rendering

- spec/asset/hello_with_content_for.ecr
- spec/asset/layout_with_yield.ecr
- spec/asset/layout_with_yield_and_vars.ecr
- spec/view_spec.cr
- src/kemal/helpers/macros.cr
Related to https://github.com/kemalcr/kemal/issues/636, I discovered that `content_for` is not capturing and yielding the correct block input inside the `ecr` view. It weirdly captures the whole content of the file
Take this for example:
`src/views/home.ecr`
```crystal
Hello <%= name %>
<% content_for "meta" do %>
<title>Kemal Spec</title>
<% end %>
```
`src/views/layout.ecr`
```crystal
<html>
<head>
<%= yield_content "meta" %>
</head>
<body>
<%= content %>
</body>
</html>
```
`src/kemal-bug.cr`
```crystal
get "/" do
render "src/views/home.ecr", "src/views/layout.ecr"
end
Kemal.run
```
When you go to `/` you'd expect the correct output with `<meta>` tag inside the `<head>` tag however this is the following output.
```
<html>
<head>
Hello world
<title>Kemal Spec</title> …
```
> content_for failing to capture the correct block input

- spec/route_handler_spec.cr
- src/kemal/ext/context.cr
Closes HTTP::Server::Response by default in HTTP::Server::Context#redirect
Does not close response by default with option to override it.
Redirections in before filters would skip processing in RouteHandler
Writing to closed HTTP::Server::Response raises `Closed stream (IO::Error)`
> Closes response by default in HTTP::Server::Context#redirect

- spec/static_file_handler_spec.cr
- src/kemal/config.cr
- src/kemal/static_file_handler.cr
Sometimes (often?) when people serve static files, they may want "pretty urls" - e.g. "/welcome" vs "/welcome/index.html". This config option enables `index.html` to be the default if the request is for a folder and the file exists, otherwise it defaults to directory listing (if enabled).
I considered just doing it in my app directly, but I belive this is a useful & missing minor feature.
Serving static html from pretty folders is now easy.
Except for the additional code, none I can think of as it's disabled by default. I'm acutally not sure where to document this though.
> Enable option for index.html to be a directories default

- shard.yml
https://github.com/crystal-loot/exception_page/pull/33
None?
> Bump `exception_page` shard to v0.3.0

- spec/filters_spec.cr
- spec/spec_helper.cr
- src/kemal/filter_handler.cr
- src/kemal/handler.cr
- src/kemal/route_handler.cr
Follow up on #564 according to @straight-shoota comment this treats `post` method as a new route.
I'm not sure why the `filters_spec` fail when ran with all the specs. It passes on its' own.
> Omitting filters fix for lowercase methods requests - Take 2 

- src/kemal/helpers/helpers.cr
When `logger` function is used, it adds logger handler after the static file handler. This causes 404 errors for static files. Default logger is also added this makes two logger handlers per every request.
Reproducer:
```crystal
public_folder "./public"
get "/hello" do |env|
"Hello!"
end
class MyCustomLogger < Kemal::BaseLogHandler
def call(context)
puts "I'm logging some custom stuff here."
call_next(context) # => This calls the next handler
end
def write(message)
STDERR.puts message # => Logs the output to STDERR
end
end
logger MyCustomLogger.new
Kemal.run
```
With this PR, `logger` function only updates the `Kemal.config` and `Kemal.run` will take care of adding logger handler.
This PR also fixes the warning when tried to run the example code for adding custom logger. …
> Fix multiple logger handlers when custom logger is used

- spec/override_method_handler_spec.cr
- src/kemal/override_method_handler.cr
This adds back `Kemal::OverrideMethodHandler` as a Kemal middleware to handle `_method` magic param in the POST request body to support `PUT, PATCH, DELETE` methods.
This is not in the default Kemal handlers.
You can enable via:
```
add_handler Kemal::OverrideMethodHandler::INSTANCE
```
P.S: This was removed in https://github.com/kemalcr/kemal/commit/207f38251a40e37700af583824fd8373b1c4cbe7 and after that there were many requests asking for the support.
> Add Kemal::OverrideMethodHandler back again

- spec/config_spec.cr
- spec/head_request_handler_spec.cr
- spec/helpers_spec.cr
- src/kemal/config.cr
- src/kemal/head_request_handler.cr
- src/kemal/helpers/helpers.cr
- src/kemal/route_handler.cr
See discussion at https://github.com/kemalcr/kemal/issues/614
> HeadRequestHandler: run GET handler and don't return the body

- src/kemal/ext/context.cr
Had a bit of a `huh?` moment when I discovered that I can't redirect to an URI, but it has to be a string. So I thought `#redirect` might as well take a `String | URI`.
Could've made an overload, but this looks nicer. Think the compiler will optimize it in any case.
Usage looks nicer.
Possibly a miniscule performance impact, in theory something has to check whether it's a string or URI now, but I believe the compiler is smarter than that.
> Allow HTTP::Server::Context#redirect to take an URL

- src/kemal.cr
I remember this change was implemented before, I see that it is reverted now and I want that change back because developers on Windows are complaining that it broke their builds.
Switches to a platform agnostic interrupt handler.
Windows support
None
> Move to Process.on_interupt

- shard.yml
- spec/websocket_handler_spec.cr
- src/kemal/config.cr
- src/kemal/ext/context.cr
- Bumps `exception_page` shard version to `~> 0.4.1`, which includes syntax highlighting and tweaked UX.
- Fixes Ameba issues, which makes CI 💚 again
- Fixes Crystal deprecation warning
> Bump `exception_page` dependency

- src/kemal/helpers/exceptions.cr
> Add message support to Kemal::Exceptions::CustomException

- spec/init_handler_spec.cr
- src/kemal/init_handler.cr
> Add `Date` header to HTTP responses

- src/kemal/static_file_handler.cr
Within the directory listing handler, the absence of an explicit charset in the content type has led to issues, particularly with directories containing non-ASCII symbols, resulting in broken displays.
Adding charset charset=UTF-8 to the Content-type header fixes this issue.
- Add `<meta charset="UTF-8">` to https://github.com/crystal-lang/crystal/blob/master/src/http/server/handlers/static_file_handler.html 
- Add charset as an optional parameter to `serve_static` config
it works
Not flexible for non UTF-8 cases.
> Directory Listing: Add UTF-8 Charset to the response Content type

- spec/run_spec.cr
- src/kemal.cr
Before this PR. When I started kemal in test mode. It would say that the app is ready and listening at xyz address. However. Kemal's server does not start when in test mode so that statement is incorrect - See last line in `Kemal.run`
> clarify startup message in test mode

- .gitattributes
- .github/workflows/ci.yml
- spec/helpers_spec.cr
- spec/run_spec.cr
- spec/view_spec.cr
- src/kemal/config.cr
- src/kemal/static_file_handler.cr
This makes Kemal work natively on Windows 11. All specs pass and also Tested with my own Kemal project with 7K Crystal LOC [Açık Türkiye](https://acikturkiye.com)
> Windows support MVP

- spec/init_handler_spec.cr
Crystal nightly has a couple new formatter rules enabled: https://github.com/crystal-lang/crystal/pull/14718
The changes are backwards-compatible, so Crystal 1.14.0 won't complain about the new format.
> `crystal tool format` with Crystal 1.15.0-dev

- shard.yml
- src/kemal/helpers/templates.cr
> Bump exception_page shard to version ~> 0.5.0

- spec/exception_handler_spec.cr
An Ameba warning was slipped through in #688
> Fix Lint/UnusedArgument in custom exception spec

- src/kemal/param_parser.cr
Alternate implementation of https://github.com/kemalcr/kemal/pull/700 using `params.all_files` as the new api without any breaking changes
> Add all_files to support multiple file uploads in parameter names ending with []

- src/kemal/static_file_handler.cr
This PR adds `return` statements after uses of `redirect_to` to halt further processing. This follows the pattern in the standard library [here](https://github.com/crystal-lang/crystal/blob/master/src/http/server/handlers/static_file_handler.cr#L80) and eliminates spurious stack traces in the output in some circumstances.
Given a simple Kemal application (tmp.cr) like the following that installs a handler that modifies the response:
```
class MyHandler < Kemal::Handler
def call(context)
context.response.content_type = "application/json"
call_next context
end
end
add_handler MyHandler.new
get "/" do
end
Kemal.run
```
And a public directory with a single sub-directory to trigger the static file handler:
```
public/
tmp/
```
A request like the following against the running …
> Return after `redirect_to`

- .github/workflows/ci.yml
Replace `format` and `ameba` jobs by a github action.
Ameba already check the code format and the github action comments on PRs, that's better than dig the errors in github actions page.
Change nothing 😅.
See linter errors directly on github PRs as comments.
None.
> Use ameba github actions.

- shard.yml
Since d4af7e216daa22111a6f906cbcdde280646ba9bf added ameba as a github action, there's no need to include ameba as developer dependency, people that still want to run ameba locally can just install it in their system.
This would remove the post-install in kemal and make some guys happy at https://forum.crystal-lang.org/t/shards-postinstall-considered-harmful/3910
Keep everything as is.
No post-install when using kemal.
Need to install ameba manually if want to run it locally.
> Remove ameba developer dependency 🔥 

- spec/config_spec.cr
- spec/helpers_spec.cr
- spec/log_handler_spec.cr
- spec/request_log_handler_spec.cr
- src/kemal.cr
- src/kemal/config.cr
- src/kemal/exception_handler.cr
- src/kemal/helpers/helpers.cr
- src/kemal/log_handler.cr
- src/kemal/null_log_handler.cr
- src/kemal/request_log_handler.cr
Kemal uses a LogHandler to log requests, this code predates the Crystal Log class so while the Kemal documentation says that logging is done using Log class, the http request log is done in a different way.
This patch deprecates:
- Kemal::Config#logger
- Kemal::Config#logger=(Kemal::BaseLogHandler)
- log(String)
- ~Kemal::LogHandler.initialize(IO)~
- Kemal::LogHandler
- NullLogHandler
and changes:
- Add Kemal::Log (Log = ::Log.for(self))
- ~Kemal::LogHandler now uses Log.~
- Add Kemal::RequestLogHandler (nodoc)
- No handler is created if logging is set to false.
Old code using custom log handlers must work as before.
Change nothing and follow with life.
Unified log interface using the standard library Log facilities.
~If there's some code using `LogHandler.new(io)` the log wont be written …
> Embrace Crystal standard Log for logging.

- spec/middleware/filters_spec.cr
- src/kemal/filter_handler.cr
This change modifies the FilterHandler to execute before_all filters when a 404 error occurs. A new test case has been added to verify that the before_all filter is triggered correctly for non-existent routes.
Implements #663
> Add before_all filter execution for 404 error in FilterHandler

- src/kemal/static_file_handler.cr
This patch simplifies the implementation of `StaticFileHandler` by inheriting most behaviour from the stdlib implementation. We only need to override the parts where Kemal provides custom behaviour.
Following the upstream implementation more closely avoids missing out on improvements (such as the fix for #710 would have been available for a long time).
This requires a `HTTP::StaticFileHandler` with patch https://github.com/crystal-lang/crystal/pull/15678
> Make use of helper methods in `StaticFileHandler`

- src/kemal/handler.cr
This PR moves the logic for `Kemal::Handler` into a separate module and then makes the class include it.
Like `HTTP::Handler` prior to being made a module `Kemal::Handler` is pretty much an interface already. It isn't intended to be initialized directly and really just serves to provide helper methods for any children class that inherits from it.
This grants the application the additional freedom to inherit from different classes while still retaining the methods provided by `Kemal::Handler`.
There shouldn't be any and everything should also be fully backwards compatible too. `Kemal::Handler` includes the new module and gets its class vars defined by an `included` macro from the module so the behavior is the same.
> Move `Kemal::Handler` logic into separate module
